### ISSUE TITLE
Inconsistent behaviour with python standard library tempfile.TemporaryDirectory

### ISSUE THREAD

**Issue by hellocoldworld** [alemigo/asynctempfile#1]
Hello! First of all great work!

The [docs](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory) for python standard `tempfile.TemporaryDirectory` says

> The directory name can be retrieved from the name attribute of the returned object. When the returned object is used as a context manager, the name will be assigned to the target of the as clause in the with statement, if there is one.

However, `asynctempfile.TemporaryDirectory` is not consistent with this, and assign self to the target of the with clause.

### To reproduce:
* Example using `tempfile.TemporaryDirectory`:

```py
import tempfile
with tempfile.TemporaryDirectory() as tmpdir:
    print(tmpdir)
 # prints /tmp/tmp5d41_0im
```

* Example using `asynctempfile.TemporaryDirectory`:

```py
import asynctempfile
async with asynctempfile.TemporaryDirectory() as tmpdir:
    print(tmpdir)
# prints <asynctempfile.temptypes.AsyncTemporaryDirectory object at 0x7f3de637ff10>
```

### Expected behaviour:
I think that for consistency with the standard library, `self.name` should be assigned to `tmpdir`.
```py
import asynctempfile
async with asynctempfile.TemporaryDirectory() as tmpdir:
    print(tmpdir)
# prints /tmp/tmp45845446 (for example)
```

**Comment by alemigo** [comment]
Thanks for this - yes I agree this make sense.  Will include in next commit.
